name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        run: |
          mkdir public
          cp -r src/* public/
          touch public/.nojekyll  # Prevent GitHub from ignoring files
          git config --global user.email "phamhbphuoc@gmail.com"
          git config --global user.name "phamhbphuoc"
          git checkout --orphan gh-pages
          git rm -rf .
          mv public/* .
          git add .
          git commit -m "Deploy GitHub Pages"
          git push -f origin gh-pages

